export const SET_MESSAGE = 'SET_MESSAGE';
export const SET_MESSAGE_REQUEST = 'SET_MESSAGE_REQUEST';
export const SET_MESSAGE_SUCCEEDED = 'SET_MESSAGE_SUCCEEDED';
export const SET_MESSAGE_FAILED = 'SET_MESSAGE_FAILED';