export const REQUEST_POKEMON_STATS = 'REQUEST_POKEMON_STATS';
export const RECEIVE_POKEMON_STATS = 'RECEIVE_POKEMON_STATS';

export const REQUEST_POKEMON_TYPES = 'REQUEST_POKEMON_TYPES';
export const RECEIVE_POKEMON_TYPES = 'RECEIVE_POKEMON_TYPES';

export const REQUEST_POKEMON_PROFILE = 'REQUEST_POKEMON_PROFILE';
export const RECEIVE_POKEMON_PROFILE = 'RECEIVE_POKEMON_PROFILE';
