export const REQUEST_POKEMON_PROFILE = 'REQUEST_POKEMON_PROFILE';
export const RECEIVE_POKEMON_PROFILE_SUCCESS = 'RECEIVE_POKEMON_PROFILE_SUCCESS';
export const RECEIVE_POKEMON_PROFILE_FAILURE = 'RECEIVE_POKEMON_PROFILE';

export const REQUEST_MOVE = 'REQUEST_MOVE';
export const RECEIVE_MOVE_SUCCESS = 'RECEIVE_MOVE_SUCCESS';
export const RECEIVE_MOVE_FAILURE = 'RECEIVE_MOVE_FAILURE';
