export const REQUEST_ALL_POKEMON = 'REQUEST_ALL_POKEMON';
export const RECEIVE_ALL_POKEMON = 'RECEIVE_ALL_POKEMON';

export const REQUEST_UPDATE_SELECTED_ID = 'REQUEST_UPDATE_SELECTED_ID';
export const RECEIVE_UPDATE_SELECTED_ID = 'RECEIVE_UPDATE_SELECTED_ID';